export interface SignatureStyle {
  id: string;
  name: string;
  model: string;
  provider: 'siliconflow' | 'huggingface' | 'pollinations' | 'xai' | 'cloudflare';
  character: string;
  theme: string;
  prompt_prefix: string;
}

export const SIGNATURE_STYLES: SignatureStyle[] = [
  {
    id: "01",
    name: "DEEP SPACE",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Cosmic / Vast / Nebula",
    theme: "The infinite mystery of the void.",
    prompt_prefix: "A hyper-realistic cinematic deep space wide-angle shot of a vibrant glowing nebula, distant crystalline planets, cinematic lighting, 8k resolution, photorealistic cosmic dust.",
  },
  {
    id: "02",
    name: "BRUTALIST ARCHITECTURE",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Structural / Concrete / Minimalist",
    theme: "The quiet power of raw material.",
    prompt_prefix: "Architectural photography of a brutalist concrete monument in a desert, sharp geometric shadows, blue sky, minimalist composition, high-end editorial look, 8k.",
  },
  {
    id: "03",
    name: "VOGUE EDITORIAL",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Fashion / High-End / Textures",
    theme: "The perfection of the human silhouette.",
    prompt_prefix: "High-end fashion editorial photography, avant-garde textured garment, dramatic lighting, soft grain, minimalist studio background, 8k masterpiece.",
  },
  {
    id: "04",
    name: "CONCEPT AUTO",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Sleek / Industrial / Matte",
    theme: "The future of the machine.",
    prompt_prefix: "Industrial design concept of a sleek futuristic hypercar, matte black finish, soft studio lighting, macro details of wheels and headlights, clean background, 8k.",
  },
  {
    id: "05",
    name: "BOTANICAL MACRO",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Organic / Vibrant / Detail",
    theme: "The intricate design of nature.",
    prompt_prefix: "Macro photography of an exotic tropical leaf with water droplets, hyper-detailed crystalline textures, soft depth of field, vibrant green tones, 8k resolution.",
  },
  {
    id: "06",
    name: "NORDIC INTERIOR",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Minimalist / Warm / Light",
    theme: "The art of living in silence.",
    prompt_prefix: "Interior design photography, modern scandinavian living room, large windows, soft natural sunlight, wooden textures, minimalist furniture, 8k.",
  },
  {
    id: "07",
    name: "EXPERIMENTAL ABSTRACT",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Fluid / Liquid / Physics",
    theme: "The dance of color and form.",
    prompt_prefix: "Abstract digital art of liquid gold and chrome clashing, high-gloss textures, flowing organic shapes, vibrant studio lighting, 8k render, impossible geometry.",
  },
  {
    id: "08",
    name: "CYBER CITYSCAPE",
    model: "flux",
    provider: "pollinations",
    character: "Nocturnal / Neon / Rain",
    theme: "The soul of the digital jungle.",
    prompt_prefix: "Cinematic wide shot of a futuristic neon-drenched city at night in the heavy rain, blade runner aesthetic, anamorphic lens flare, gritty realistic textures, 8k.",
  },
  {
    id: "09",
    name: "STREET DOCUMENTARY",
    model: "flux",
    provider: "pollinations",
    character: "Candid / Gritty / Realism",
    theme: "Humanity in the concrete void.",
    prompt_prefix: "Candid documentary street photography, rainy urban alleyway, moody lighting, cinematic film grain, hyper-detailed skin textures, nocturnal city soul.",
  },
  {
    id: "10",
    name: "PRODUCT DESIGN",
    model: "flux",
    provider: "pollinations",
    character: "Minimalist / Tech / Sleek",
    theme: "The perfection of functional art.",
    prompt_prefix: "Industrial product photography, minimalist tech accessory, matte finish, soft rim lighting, hyper-detailed textures, clean white studio background, 8k.",
  },
  {
    id: "11",
    name: "SURREAL PORTRAIT",
    model: "@cf/bytedance/stable-diffusion-xl-lightning",
    provider: "cloudflare",
    character: "Neo-Realism / Holographic",
    theme: "The evolution of the human face.",
    prompt_prefix: "A hyper-realistic studio portrait of a person with holographic digital implants, iris macro photography, dramatic cinematic lighting, 8k resolution.",
  },
  {
    id: "12",
    name: "MONO GEOMETRY",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "B&W / Shadow / Form",
    theme: "The contrast of absolute dark.",
    prompt_prefix: "Minimalist black and white art photography, high contrast geometric shadows, abstract architectural lines, dramatic light, grainy film texture.",
  },
  {
    id: "13",
    name: "DRONE LANDSCAPE",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Top-Down / Patterns / Nature",
    theme: "The earth's patterns from above.",
    prompt_prefix: "High-end drone photography of a winding mountain road in Autumn, vibrant orange and red trees, top-down perspective, cinematic lighting, 8k.",
  },
  {
    id: "14",
    name: "LUXURY INTERIOR",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Stone / Glass / High-End",
    theme: "The peak of human living.",
    prompt_prefix: "Architectural interior photography of a luxury minimalist villa with a glass floor over water, soft golden hour sunlight, hyper-detailed stone textures, 8k.",
  },
  {
    id: "15",
    name: "EXPERIMENTAL MACRO",
    model: "black-forest-labs/FLUX.1-schnell",
    provider: "siliconflow",
    character: "Details / Micro / Crystalline",
    theme: "The architecture of the small.",
    prompt_prefix: "Extreme macro photography of ice crystals forming on a dark metal surface, fractal patterns, soft cinematic lighting, hyper-realistic crystalline textures, 8k.",
  },
];
